@Supermarket.Api_HostAddress = http://localhost:5033
  
GET {{Supermarket.Api_HostAddress}}/api/products/?ormType=Dapper
Accept: application/json

###

### Filtrar por name
GET {{Supermarket.Api_HostAddress}}/api/products/filter?ormType=EfCore?name=secco
Accept: application/json

###

### Filtrar por stock
GET {{Supermarket.Api_HostAddress}}/api/products/filter?stock=20
Accept: application/json

###

### Filtrar por price
GET {{Supermarket.Api_HostAddress}}/api/products/filter?price=2000
Accept: application/json

###

### Filtrar por varios parámetros
GET {{Supermarket.Api_HostAddress}}/api/products/filter?name=secco&stock=5000&price=2000
Accept: application/json

###


### Alta (crear un producto)
POST {{Supermarket.Api_HostAddress}}/api/products
Content-Type: application/json
Accept: application/json

{
  "name": "Coca cola 3l",
  "description": "marca coca cola",
  "price": 4000,
  "stock": 500,
  "proveedorID": 1
}

###

### Baja (eliminar un producto por ID)
DELETE {{Supermarket.Api_HostAddress}}/api/products/10
Accept: application/json

###

### Modificacion (actualizar un producto)
PUT {{Supermarket.Api_HostAddress}}/api/products
Content-Type: application/json
Accept: application/json

{
  "id": 9,
  "name": "Harina integral bolsa de 10 kilos",
  "description": "marca cholita",
  "price": 9000,
  "stock": 80,
  "supplierId": 1
}

###

  ### Alta (crear una venta)
POST {{Supermarket.Api_HostAddress}}/api/ventas
Content-Type: application/json
Accept: application/json

{
  "fecha": "2025-05-31T10:00:00",
  "clientId": 1,
  "total": 5500.50,
  "detalles": [
    {
      "productId": 5,
      "quantity": 3,
      "unitPrice": 3.42
    },
    {
      "productId": 9,
      "quantity": 1,
      "unitPrice": 40.50
    },
    {
      "productId": 4,
      "quantity": 1,
      "unitPrice": 40.50
    }
  ]
}

###

### Consultar ventas por cliente y producto
GET {{Supermarket.Api_HostAddress}}/api/ventas/filter?clienteId=1&productId=2
Accept: application/json

###